name: workflow for c/c++
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SNYK_API: ${{ secrets.SNYK_API }}

    steps:
    - uses: actions/checkout@v2

     # Install & prepare Snyk
    - run: npm install --location=global snyk

    # Authenticate Snyk      
    - run: snyk auth ${{ secrets.SNYK_TOKEN }}

    # Run Snyk OpenSource Test
    - name: Snyk OpenSource Test
      run: 
          snyk test --unmanaged --print-dep-paths || true
          
    # Run Snyk OpenSource Monitor
    - name: Snyk OpenSource Monitor
      run: 
          snyk monitor --unmanaged --print-dep-paths --org=pipeline-examples || true
          
    # Run Snyk Code Test
    - name: Snyk Code Scanning
      run: snyk code test || true
